# Generated by Django 4.1.6 on 2023-05-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_diaria_complemento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaria',
            old_name='candidatos',
            new_name='candidatas',
        ),
    ]
