# Generated by Django 4.1.6 on 2023-05-31 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_diaria_preco_alter_diaria_valor_comissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transacao_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('diaria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.diaria')),
            ],
        ),
    ]
