# Generated by Django 4.1.6 on 2023-07-15 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='candidatas',
            field=models.ManyToManyField(blank=True, related_name='candidatas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EnderecoDiarista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=60, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(max_length=30)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='endereco', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
