# Generated by Django 4.1.6 on 2023-04-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_alter_servico_porcentagem_comissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='porcentagem_comissao',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
